pipeline {
    agent any

    stages {
        stage('Preparation') {
            steps {
                echo 'Hello from Github';
                sh 'node -v';
                sh 'npm -v';
            }
        }
    }
}
