name: CI - CodeReview Action

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to fe-agencies-reto
      uses: actions/checkout@v4

    - name: Setting NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install and build
      run: |
        npm ci
        # npm run build --if-present
        cp devops/sonar/sonar-project.properties . && ls -lha

    - name: Run tests
      run: npm test

    - name: Official SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.3.0


