name: CodeReview Manual

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to analyze. By default is develop'
        required: true
        default: 'develop'
        type: string
  push:
    branches:
      - 'feature/**-code-review'

jobs:
  BuildTestsAndQuality:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout to fe-agencies-reto
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'push' && github.ref || github.event.inputs.branch }}

    - name: Setting NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm build

    - name: Run tests
      run: npm test

    - name: Code Quality, Security and Static Analysis
      uses: SonarSource/sonarqube-scan-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dproject.settings=devops/sonar/sonar-project.properties



