name: Ligth Deploy to DEV (no run tests)

on:
  workflow_dispatch:

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-22.04
    environment: DEV

    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4
      with:
        ref: 'develop'

    - name: Setting NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Getting package version
      run: |
        sudo apt-get install jq
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: dadadev88/{{ env.APP_NAME }}:latest




