env:
  APP_NAME: 'fe-agencies-reto'
  DOCKER_IMG_TAG: ghcr.io/dadadev88/dev/fe-agencies-reto:latest

name: workflow-dev-ligth-deploy
run-name: Deploying ${{ github.event.inputs.targetBranch || 'develop' }} branch to DEV

on:
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'Branch to deploy. By default is develop'
        type: string

jobs:
  Build:
    runs-on: ubuntu-22.04
    environment: DEV

    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.targetBranch || 'develop' }}

    - name: Setting NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
        cat src/app/shared/components/ui/bcp-header/bcp-header.component.html

    # ! TODO: Delete
    - name: Getting package version
      run: |
        sudo apt-get install jq
        VERSION=$(jq -r '.version' package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "The package version is $VERSION"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        echo "Building Docker image ${{ env.DOCKER_IMG_TAG }}"
        docker build -t ${{ env.DOCKER_IMG_TAG }} .
        echo "Pushing Docker image ${{ env.DOCKER_IMG_TAG }} to registry"
        docker push ${{ env.DOCKER_IMG_TAG }}

  Deploy:
    runs-on: self-hosted
    needs: Build

    steps:
      - name: Deploying webapp
        run: |

          if [ "$(docker ps -a -q -f name=${{ env.APP_NAME }})" ]; then
            echo 'Eliminando contenedor ${{ env.APP_NAME }}'
            docker rm -f $(docker ps -a -q -f name=${{ env.APP_NAME }})
          fi

          echo 'Creando contenedor ${{ env.APP_NAME }}'
          docker run -d \
            --name ${{ env.APP_NAME }} \
            --restart always \
            --pull always \
            -p 80:80 \
            ${{ env.DOCKER_IMG_TAG }}




