name: workflow-deploy-prod
run-name: Deploying ${{ github.ref_name }} branch to PROD. Branches = HEAD <${{ github.head_ref }}> | BASE <${{ github.base_ref }}>

on:
  pull_request:
    branches:
      - 'RC-CERT**'

env:
  AZURE_WEBAPP_NAME: wappeus2bcptip01
  DOCKER_IMG: ghcr.io/dadadev88/fe-agencies-reto

jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Branches validations
        run: |
          echo "Branches = HEAD <${{ github.head_ref }}> | BASE <${{ github.base_ref }}>"
          echo "${{ startsWith(github.head_ref, 'RC-CERT') && github.base_ref == 'master' }}"

  BuildAndDeploy:
    if: ${{ startsWith(github.head_ref, 'RC-CERT') && github.base_ref == 'master' }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: PROD

    steps:
    - name: Checkout to branch
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.DOCKER_IMG }}:${{ github.head_ref }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.DOCKER_IMG }}:${{ github.head_ref }}
