name: workflow-deploy-dev-light
run-name: Deploying ${{ github.ref_name }} branch to DEV

env:
  APP_NAME: 'fe-agencies-reto'
  DOCKER_IMG: ghcr.io/dadadev88/dev/fe-agencies-reto

on:
  workflow_dispatch:
    # inputs:
    #   targetBranch:
    #     description: 'Branch to deploy. By default is develop'
    #     type: string

jobs:
  Build:
    name: Building webapp
    runs-on: ubuntu-22.04
    outputs:
      PKG_VERSION: ${{ steps.pkg-version.outputs.PKG_VERSION }}

    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4
      # with:
      #   ref: ${{ github.event.inputs.targetBranch || 'develop' }}

    # echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV -> $\{{ env.PKG_VERSION }}
    - name: Getting package version
      id: pkg-version
      run: |
        sudo apt-get install jq && PKG_VERSION=$(jq -r '.version' package.json)
        echo "The package version is $PKG_VERSION"
        echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        # context: . # Requerido si se hace checkout a una rama diferecta a la del workflow
        push: true
        tags: ${{ env.DOCKER_IMG }}:${{ steps.pkg-version.outputs.PKG_VERSION }}

  Deploy:
    name: Deploying webapp
    runs-on: self-hosted
    needs: Build

    steps:
      - name: Deploying webapp
        run: |
          if [ "$(docker ps -a -q -f name=${{ env.APP_NAME }})" ]; then
            echo 'Eliminando contenedor ${{ env.APP_NAME }}'
            docker rm -f $(docker ps -a -q -f name=${{ env.APP_NAME }})
          fi

          echo 'Creando contenedor ${{ env.APP_NAME }}'
          docker run -d \
            --name ${{ env.APP_NAME }} \
            --restart always \
            --pull always \
            -p 80:80 \
            ${{ env.DOCKER_IMG }}:${{ needs.Build.outputs.PKG_VERSION }}




