name: workflow-deploy-cert
run-name: Deploying develop branch to CERT

env:
  APP_OUTPUR_DIR: "dist/fe-agencies-reto"

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  BuildAndDeployJob:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: CERT

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ${{ env.APP_OUTPUR_DIR }}

  BuildRC:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Create RC
    environment: CERT

    steps:
      - name: Checkout to develop branch
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Getting package information
        uses: dadadev88/node-package-info@v1.0.0
        id: node-package-info
        with:
          path: 'package.json'

      - name: Push release candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PKG_NAME: ${{ steps.node-package-info.outputs.name }}
          PKG_VERSION: ${{ steps.node-package-info.outputs.version }}
        run: |
          echo "Package name: $PKG_NAME"
          echo "Package version: $PKG_VERSION"

          RC_BRANCH="RC-CERT_${PKG_NAME}_${PKG_VERSION}_$(date "+%Y%m%d-%H%M%S")"
          git checkout -b $RC_BRANCH
          git push origin $RC_BRANCH
          echo "Release candidate generated -> $RC_BRANCH"

  ClosePullRequestJob:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: CERT

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
