name: workflow-code-review-pr
run-name: Code review for "${{ github.head_ref }}" branch on Pull Request

env:
  SONAR_CLOUD_ORG: 'dadadev88'

on:
  pull_request:
    branches:
      - develop

jobs:
  BuildTestsAndQuality:
    name: Build, tests and quality code
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout to repository
      uses: actions/checkout@v4

    - name: Setting NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm ci
        npm run build

    - name: Run tests
      run: npm test

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dproject.settings=devops/sonar/sonar-project.properties
          -Dsonar.organization=${{ env.SONAR_CLOUD_ORG }}
          -Dsonar.projectVersion=1.0



