name: workflow-deploy-cert
run-name: Deploying develop branch to CERT

env:
  APP_OUTPUR_DIR: "dist/fe-agencies-reto"

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop

jobs:
  BuildAndDeployJob:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: CERT

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ${{ env.APP_OUTPUR_DIR }}

  BuildRC:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Create RC
    environment: CERT

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Push release candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get install jq && RC_BRANCH=RC-CERT_$(jq -r '.version' package.json)_$(date "+%Y%m%d-%H%M%S")
          git checkout -b $RC_BRANCH
          git push origin $RC_BRANCH
          echo "Release candidate generated -> $RC_BRANCH"

  ClosePullRequestJob:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: CERT

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
